name: ancienttourguidance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  apple_maps_flutter: ^1.0.2
  persistent_bottom_nav_bar: ^6.2.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  appsflyer_sdk: ^6.17.5
  app_tracking_transparency: ^2.0.6+1
  webview_flutter_wkwebview: ^3.23.1
  url_launcher: ^6.3.2
  external_app_launcher: ^4.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/